### PR TITLE
Fixes & extensions

### PR DESCRIPTION
**Pull request by bcipolli**
- Fixed up latex links & images to markdown.
- Fixed up github URL (@binarybottle hope this is OK)
- Added text & image on post-hackathon work.

@binarybottle @akeshavan please review!

### CODE REVIEW

**Comment by bcipolli** [comment]
Here's the link to the visible MD file:
https://github.com/Brainhack-Proceedings-2015/Keshavan_HBM_BrainShapeVis/blob/bc/brainhack-report.md

**Comment by binarybottle** [comment]
@bcipolli -- what's with the broken Dynamic poster visualization?
Shouldn't we move roygbiv from binarybottle to nipy/mindboggle?

**Comment by bcipolli** [comment]
@binarybottle I fixed the image link issue.

> Shouldn't we move roygbiv from binarybottle to nipy/mindboggle?

How would we do that? It's its own repo. Make it a submodule, or ... ?

**Comment by binarybottle** [comment]
I was thinking it would be better off if maintained by the nipy community (even though it isn't python code), either as its own repo, or as a directory within mindboggle (nipy/mindboggle/roygbiv).  What do you think?

**Comment by bcipolli** [comment]
That would be fine. I think keeping it in it's own repo is better if possible; it's not obvious that it's related to mindboggle, the community contributing to mindboggle isn't too large yet (so adding it to mindboggle won't help it get contributors), and it would be more visible for people searching for a way to do 3D brain surfaces in the browser.

**Comment by bcipolli** [comment]
(but I'm cool either way)

**Comment by binarybottle** [comment]
I think you're right -- I'll keep it in its own repo...

**Pull request merged**
